version: '3.8'
services:
  server:
    build: .
    command: uvicorn democratizing.main:app --host 0.0.0.0 --reload
    container_name: democratizingdata_api
    env_file:
      - dev.env
    volumes:
      - ./democratizing/:/srv/www/democratizing
    ports:
      - 8000:8000
